### PR TITLE
[Mapper] Add InMapper & OutMapper

### PR DESCRIPTION
**Pull request by dreymonde**
Check out the README:
https://github.com/Zewo/Zewo/blob/genericMapper/Modules/Mapper/README.md

### CODE REVIEW

**Comment by Danappelxx** [comment]
Looks good from afar! Could you add some tests and doc comments (just method-level stuff, like [here](https://github.com/Zewo/POSIX/blob/master/Sources/POSIX/Lock.swift)) to make it easier to understand how this works? What's `ContextualMapper` for?

**Comment by dreymonde** [comment]
@Danappelxx yes, sure, I'll add some tests and docs. You can check out Mapper PR at Quark, it's thoroughly tested, I will just migrate them from there)

**Comment by Danappelxx** [comment]
Circle will work if you update Scripts/Travis/install.sh from master :)

**Comment by dreymonde** [comment]
@Danappelxx sorry, I don't understand what you mean :)

**Comment by Danappelxx** [comment]
Circle is failing because there's an outdated swift install script on your
branch. Master has an updated one, so if you replace yours with it the
build should pass.

**Comment by dreymonde** [comment]
@Danappelxx now I get it, thanks 👍

**Comment by paulofaria** [comment]
let's have this merged for 0.15.0 (:

**Comment by paulofaria** [comment]
@dreymonde can we finally merge this? haha it's done right? just need a rebase?

**Comment by dreymonde** [comment]
@paulofaria yes, I think it's ready :) Maybe just rename `Keys` to `MappingKeys`, what do you think? I'm afraid of name conflicts.

**Pull request merged**
