### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by antonmes**
Readme looks little bit overloaded for quick start. 
I tried to improve it, please review. 🍻

### CODE REVIEW

**Comment by Danappelxx** [comment]
LGTM (though I would squash the commits). @paulofaria

**Comment by paulofaria** [comment]
The only thing I'm worried is about swiftenv.

> You can skip swiftenv step and some swiftenv instructions below if you already have DEVELOPMENT-SNAPSHOT-2016-02-08-a in your PATH

I think it would be nice if we encourage the use of `swiftenv` with `.swift-version` files (local swift version). Also, swiftenv's hombrew installation doesn't work properly. So I would at least add a notice suggesting the git clone installation process.

**Comment by paulofaria** [comment]
Other than that a squash would be nice as well! (;

**Comment by antonmes** [comment]
done.

**Comment by paulofaria** [comment]
Did you check brew with the `--head`? does it really work?

**Comment by paulofaria** [comment]
I only tried the manual `git clone`.

**Comment by paulofaria** [comment]
If it works as expected feel free to merge! (:

**Pull request merged**
