### PR TITLE
[Axis] Clean up Map's API, making it more predictable and simple

### PR DESCRIPTION
**Pull request by Danappelxx**
These are my suggested changes, but let's keep discussing this.

What's in here:
- [x] Remove ExpressibleByNilLiteral. Making `Map.null` == `nil` is confusing, and is more similar to the null pointer mechanism that Swift discourages rather than the optional pattern. Correctness > convenience in this case IMO.
- [x] Remove `get` in favor of subscript
- [x] Remove `set` in favor of subscript
- [x] Remove `remove` in favor of subscript
- [x] Make subscript optional
- [x] Add `asInferred` method which uses type inference. It is the only generic method.
- [ ] Reintegrate with Mapper (there were API conflicts)
- [ ] Remove `MapRepresentable` in favor of just `MapFallibleRepresentable`. Having two similar API's is confusing, especially since being `MapInitiliazable` and `MapRepresentable` doesn't give you `MapConvertible`.
- [ ] Remove unused errors from enum
- [ ] Any ideas?

There is now exactly one way to index map (subscript), and several ways to unbox the type (`int`, `isInt`, `asInt()`, `asInferred`):
```swift
let map: Map = [
    "string": "hello world",
    "array": [1, 2, 3, 4, 5],
    "dictionary": [
        "string": "nested hello world",
        "array": [6, 7, 8, 9, 10]
    ]
]

let a: Map? = map["dictionary", "array", 2]
let b: Int? = map["dictionary", "array", 2]?.int
let c: Int = try map["dictionary", "array", 2].map.asInt()
let d: Int = try map["dictionary", "array", 2].map.asInferred()
```

cc @paulofaria @robertjpayne @dreymonde

### CODE REVIEW

**Comment by Danappelxx** [comment]
The one thing I'm not quite happy with is that the optional subscripts mean that you either have to use `?` or `.map` to use the other getters. This is fine for optional getters `.int`, but is less nice for throwing getters as their convenience is exactly that they are not optional. Perhaps we could move `as<Type>` onto `MapFallibleRepresentable`?

**Comment by Danappelxx** [comment]
Also, @dreymonde how would `Mapper` fit into all of this? I commented it out for now because there were conflicts with `asArray()`. Perhaps Mapper's requirement of `asArray` could throw instead of returning nil? Or maybe make it a computed property `array`? That way we don't have to add any conflicting methods to conform to it.

**Comment by robertjpayne** [comment]
I LIKE IT! 👍

**Comment by dreymonde** [comment]
My opinion on naming:
I don’t like the `asInt`/`int` style which (as I remember) came from **SwiftyJSON**, because it simply repeats type information which is already there. By using these kind of names, we omit several really powerful features of Swift. So I prefer replacing `asInt()`, `asString()`, `asBool()` and so on with `get() throws -> Int`, `get() throws -> String`, `get() throws -> Bool` and so on (`get` is not the best name, I agree, but that’s not the main point here). So not _generic_, but overloading. And that won’t lose in usability/convenience too — you can always write:

``` swift
let number = try map["key"].map.get() as Int
```

And, of course, there are a dozens of situations where type information is already available, so you don’t even have to write that `as Int`, but with `asInt`/`int` style you still have to.

And my point is that there should be no generic methods at all — `asInferred` is tricky and way too subtle, as for me.

**Comment by dreymonde** [comment]
Maybe it sounds too radical, but we should at least consider this approach.

**Comment by Danappelxx** [comment]
I really want to avoid type ambiguity as much as possible. Consider the following example

``` swift
route.post { request in
    let username = try request.content["username"].asString()
    let username = try request.content["username"].get() as String
    // ...
}
```

Notice how you're repeating type information either way. Furthermore, the first example is much more obvious to a beginner. 

Really, the only time when you don't need to hint the type is when you're working in an initializer. In those cases, you can use `asInferred()`, or better yet `Mapper` which is exactly meant for that sort of stuff.

> And my point is that there should be no generic methods at all — asInferred is tricky and way too subtle, as for me.

Could you expand on this? I lowered it to one generic method, which we need either way to support `MapInitializable`. What is tricky and/or subtle about it (except for the perhaps inaccurate naming)?

**Comment by dreymonde** [comment]
1. There is no type repeating in your example. As type repeating, I consider this:

``` swift
func statusCode(from map: Map) -> Int? {
    return try? map["statusCode"].map.get()
    // vs
    return try? map["statusCode"].map.asInt()
}
```

I’m not saying that it’s very important, it’s just my opinion that `asInt`/`asString`/etc. naming pattern is a bit unswifty, and «type-hidden» thing is more consistent with new API design guidelines.
1. As I understand, `asInferred` works with `MapInitializable`. That’s why it’s tricky. Swift insists that this type of conversion should be done via initializers. So, in my opinion, it’s much better to do:

``` swift
let headers = try Headers(from: map)
```

than

``` swift
let headers = try map.asInferred() as Headers
```

Even though the second example can look nicer in some places.

And the whole concept of some `asInferred` looks strange and alien, and will be difficult for beginners to understand. I think it’s better to avoid usage of word «inferred» in an API.

**Comment by Danappelxx** [comment]
I just pushed a commit which changes
```swift
try map["string"].map.asString()
```
to
```swift
map["string"].asString()
```
the following is still legal, though it's only there because optionals are built into the language
```swift
map["string"]?.asString()
map["string"]?.string
```

@dreymonde:

>I’m not saying that it’s very important, it’s just my opinion that asInt/asString/etc. naming pattern is a bit unswifty, and «type-hidden» thing is more consistent with new API design guidelines.

I agree with this, and when the type is known you should use a type inference method. `asInferred` is a bad name, I'm completely open to better ones. However, I would prefer the names to be consistent. Any ideas? `get`, `getString`?

>As I understand, asInferred works with MapInitializable. That’s why it’s tricky. Swift insists that this type of conversion should be done via initializers.

Ah, this is a good point. I'm not really sure what to do about it, because I would argue it's expected behavior for nested maps. Using the initializer is still possible - both of these are currently legal:
```swift
func headers(from map: Map) throws -> Headers {
    return try map["headers"].asInferred()
}
func headers(from map: Map) throws -> Headers {
    return try Headers(map: map["headers"].map)
}
```
Actually, that example shows another spot that we're missing with the optional subscripts...

**Comment by dreymonde** [comment]
@Danappelxx if we take your path, I propose choosing `asString`, `asInt` and so on and _no_ generic/inferred method. `MapInitializable` should really use initializer for that.

**Pull request closed without merging**
