### PR TITLE
Add instructions for fixing 'no such module' when trying to link to a C module

### PR DESCRIPTION
**Pull request by Lidbetter**

### CODE REVIEW

**Comment by donut** [comment]
It's been unclear to me on what target that needs to be added. Do I need to go through each dependency that depends on a  C library and add this or does it work to add it to the main project target?

**Comment by Lidbetter** [comment]
The screenshot has the main project selected. I will make it clear in text too.

**Comment by donut** [comment]
So, while adding this to the project seems to work for most cases, I ended up having to add it directly to my TCP sub-dependency target as well.

Package.swift:

``` swift
import PackageDescription

let package = Package(
    name: "Example",
    dependencies: [
        .Package(url: "https://github.com/VeniceX/File.git",
                 majorVersion: 0, minor: 7),
        .Package(url: "https://github.com/VeniceX/HTTPSClient.git",
                 majorVersion: 0, minor: 7),
        .Package(url: "https://github.com/Zewo/Base64.git",
                 majorVersion: 0, minor: 8),
        .Package(url: "https://github.com/Zewo/JSON.git",
                 majorVersion: 0, minor: 9),
        .Package(url: "https://github.com/Zewo/Log.git",
                 majorVersion: 0, minor: 8),
        .Package(url: "https://github.com/Zewo/Mapper.git",
                 majorVersion: 0, minor: 7),
        .Package(url: "https://github.com/Zewo/OpenSSL.git",
                 majorVersion: 0, minor: 7)
    ]
)
```

**Comment by Danappelxx** [comment]
Ok, this is no longer necessary for `05-09` - the current instructions in the README should be correct. We accidentally pushed a tag that works on the latest snapshot but not on `05-09`, but its now been shifted to the next minor. Sorry for the trouble!

**Pull request closed without merging**
